layout_spectrum: 0.2365591
color:
  saturation: 0.1003584
  brandStrength: 0.9247312
  lightness: 0.2096774
  brandColors:
    - '#3B393A'
    - '#E9E9E7'
    - '#BEBEB3'
  rhythmicContrast: 0.5734767
typography_spectrum: 0.8620071
name: Varnost
