name: Varnost
favicon: null
layout_spectrum: 0.25837
typography_spectrum: 0.41369
title: Varnost Development Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8c8c8c'
    - '#070707'
    - '#808080'
    - '#999999'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
